services:
  detector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: detector-server
    ports:
      - "5000:5000"
    environment:
      SERVER_IP: "192.168.1.22" # Colocar o IP do servidor (ip do seu computador)
    volumes:
      - .:/app/server
    restart: unless-stopped